### ISSUE TITLE
matrix as input

### ISSUE THREAD

**Issue by pabloloyola** [mhepaixao/Travelling-Salesman-Problem-with-Ant_Q-in-Java#1]
Hi, I am exploring your implementation and, as I understand, I can pass a file with x,y coordinates or a matrix.
In the case  of a matrix, I am a little bit confused in terms of the format.  In the InstanceReader.java file, we have the `getEdgesValuesMatrix` method

>  * The distance matrix must be in one of the formats that follows:
    * Let n be the number of cities.
    * 1) Symmetric matrix, where the first line is A1, A2 to A1, An. And the last line is An-1, An.

Does this mean that if, for example I have 5 nodes . a , b , c, d ,e and  (a,b), (a,c) ,(b,d), (d,e), (b,e)
the file should be
```
a b
a c
b d
b e
d e
```
? 
Thanks!

**Comment by mhepaixao** [comment]
Hi, it's been a long time since I've coded this, so bear in mind I might be wrong :-)

I believe this method is used to to get the distance between each city, or weights of the edges in the graph. Therefore, I believe the format must be:

aa ab ac ad ae
ba bb bc bd be
ca cb cc cd ce
da db dc dd de
ea eb ec ed ee

Where ab, for example is the distance between city a and city b.

Let me know if it worked for you :-)

**Comment by pabloloyola** [comment]
HI, yeah, you are right. it is a distance matrix.
I am interested on inputting a adjacency matrix, as i want to work with graphs. 
Thanks for your help

**Comment by mhepaixao** [comment]
I see. I'm glad I was right. I'll close this one, but feel free to open another issue if you need
